"""設定から小さな caller workflow を決定的に生成する。"""

import difflib
import json
from pathlib import Path

from .config import ACTION_REPOSITORY, WORKFLOW_PATH, relative_path
from .contracts import Config


def render(config: Config, config_path: str, output_path: str) -> str:
    relative_path(config_path)
    relative_path(output_path)
    ref = config["action_ref"]
    workflows = json.dumps(config["ci"]["workflows"], ensure_ascii=False)
    paths = json.dumps([config_path, output_path], ensure_ascii=False)
    return f"""# Generated by pr-merge-readiness-action. Do not edit by hand.
# Source: {config_path}
name: PR Merge Readiness

on:
  workflow_run:
    workflows: {workflows}
    types: [in_progress, completed]
  pull_request_target:
    types: [opened, reopened, synchronize, edited, ready_for_review, converted_to_draft, closed]
  workflow_dispatch:
    inputs:
      pr-number:
        description: PR number (empty = all open PRs)
        type: string
        required: false
      update-labels:
        description: Update labels for all open PRs
        type: boolean
        default: false
  pull_request:
    paths: {paths}
  push:
    paths: {paths}

permissions:
  contents: read

jobs:
  validate:
    if: github.event_name == 'pull_request' || github.event_name == 'push'
    uses: {ACTION_REPOSITORY}/.github/workflows/validate.yml@{ref}
    with:
      config-path: {json.dumps(config_path)}
      output-path: {json.dumps(output_path)}
      action-ref: {ref}
  readiness:
    if: github.event_name != 'pull_request' && github.event_name != 'push'
    permissions:
      contents: read
      actions: read
      checks: write
      statuses: read
      issues: write
      pull-requests: write
    uses: {ACTION_REPOSITORY}/{WORKFLOW_PATH}@{ref}
    with:
      config-path: {json.dumps(config_path)}
      action-ref: {ref}
      pr-number: ${{{{ inputs.pr-number || '' }}}}
      update-labels: ${{{{ inputs.update-labels || false }}}}
"""


def generate_workflow(config: Config, config_path: Path, output_path: Path, check: bool) -> int:
    # 出力にローカル絶対パスを混ぜない。利用側 repository のルートから実行する。
    desired = render(config, config_path.as_posix(), output_path.as_posix())
    actual = output_path.read_text() if output_path.is_file() else ""
    if check:
        if desired != actual:
            print(
                "".join(
                    difflib.unified_diff(
                        actual.splitlines(True),
                        desired.splitlines(True),
                        fromfile=str(output_path),
                        tofile="generated",
                    )
                )
            )
            return 1
        return 0
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(desired)
    return 0
